name: Run checks

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - "**/*.nix"

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.runner }}
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/magic-nix-cache-action@main"
      - name: Flake build
        run: nix develop --command build
      - name: Check formatting
        run: |
          git ls-files '*.nix' | xargs nix develop --command alejandra --check
